name: Deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: install dependecies
      run: npm install

    - name: Run Test
      run: npm test

    - name: Set up SHH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to vps
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            if [ ! -d CICD1 ]; then
              git clone git@github.com:Sunnyday911/CICD.git CICD1;
            fi &&
            cd CICD1 &&
            git pull origin main &&
            docker compose down ||
            true &&
            docker compose up -d --build
          "
